<?php

namespace AppBundle\Repository;

/**
 * ChallengeAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
