<?php

namespace AppBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;


class TestRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMaxID(){
        $query = $this
            ->createQueryBuilder('t')->select('max(t.id)')->getQuery();
        return $query->getOneOrNullResult();
    }
}
