<?php

namespace AppBundle\Repository;

/**
 * TestQuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestQuestionsRepository extends \Doctrine\ORM\EntityRepository
{
}
