<?php

namespace AppBundle\Repository;

/**
 * UserTestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTestsRepository extends \Doctrine\ORM\EntityRepository
{
}
