<?php

namespace AppBundle\Repository;

/**
 * UserTestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTestsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTestsForUser($userId)
    {
        $qb = $this->createQueryBuilder('ut');
        $qb
            ->select('t.id, ut.userScore,t.title, t.totalScore, ut.usedTime')
            ->leftJoin(
                'AppBundle\Entity\Test',
                't',
                'WITH',
                'ut.test = t.id'
            )
            ->where('ut.user = :user')
            ->setParameter('user', $userId)
            ->orderBy('ut.userScore', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
