<?php

namespace AppBundle\Repository;

use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserProviderInterface
{
    public function loadUserByUsername($username)
    {
        // TODO: Implement loadUserByUsername() method.
    }

    public function refreshUser(UserInterface $user)
    {
        $id = $user->getId();
        $refreshedUser = $this->find($id);
        if (null === $refreshedUser) {
            throw new UsernameNotFoundException(sprintf('User with id %s not found', $id));
        }
        return $refreshedUser;
    }

    /**
     * Whether this provider supports the given user class.
     *
     * @param string $class
     *
     * @return bool
     */
    public function supportsClass($class)
    {
        $thisClass = get_class($this);
        return $class === $thisClass || is_subclass_of($class, $this->class);
    }

    public function findByUsernameOrEmail($username)
    {
        $query = $this->createQueryBuilder('u')
                      ->where("u.username = :param")
                      ->orWhere("u.email = :param")
                      ->setParameter("param", $username);
        
        return $query->getQuery()->getOneOrNullResult();
    }

    public function getUsersPerPage($pageNumber, $numberOfUsers)
    {
        $query = $this->createQueryBuilder('u')
                      ->orderBy("u.id","DESC")
                      ->setFirstResult($pageNumber * $numberOfUsers)
                      ->setMaxResults($numberOfUsers);

        return $query->getQuery()->getResult();
    }
    
    public function getUsersByType($type)
    {
        $query = $this->createQueryBuilder('u')
                      ->where("u.type = :param")
                      ->orderBy("u.id","DESC")
                      ->setParameter("param", $type);
        
        return $query->getQuery()->getResult();
    }

}

