app:
    resource: "@AppBundle/Controller/"
    type:     annotation

security_register:
    path: /register
    defaults: { _controller: AppBundle:Security:register }

security_login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

security_login_auto:
    path: /login/auto/{username}
    defaults: { _controller: AppBundle:Security:autoLogin }

security_logout:
    path: /logout
    defaults: { _controller: AppBundle:Security:logout }

home:
    path: /
    defaults: { _controller: AppBundle:Challenge:index}

regulations:
    path: /regulations
    defaults: { _controller: AppBundle:Default:regulations}

category_list:
    path: /categories
    defaults: { _controller: AppBundle:Category:listCategories }

question_list:
    path: /questions/{cid}
    defaults: { _controller: AppBundle:Question:listQuestionsPerCategory }

question_edit:
    path: /question/edit/{cid}/{id}
    defaults: { _controller: AppBundle:Question:edit }

delete_question:
    path: /question/delete/{cid}/{id}
    defaults: { _controller: AppBundle:Question:delete }

test_ranking:
  path: /test/ranking/{id}
  defaults: { _controller: AppBundle:Test:getRankingByTest }

all_question_list:
    path: /questions
    defaults: { _controller: AppBundle:Question:listAllQuestions }

test_list:
    path: /test/{cid}
    defaults: { _controller: AppBundle:Test:listTestsPerCategory }

test_list_all:
    path: /test
    defaults: { _controller: AppBundle:Test:listAllTests}

delete_test:
    path: /test/delete/{cid}/{id}
    defaults: { _controller: AppBundle:Test:delete }

test_generate:
    path: /test/generate/{cid}
    defaults: { _controller: AppBundle:Test:generate}

test_show:
    path: /test/show/{tid}
    defaults: { _controller: AppBundle:Test:showQuestionsInTest}

take_test:
    path: /test/take/{tid}
    defaults: { _controller: AppBundle:Test:takeTest}

solve_test:
    path: /test/solve/{tid}
    defaults: { _controller: AppBundle:Test:solveTest }
    
delete_challenge:
    path: /challenge/delete/{id}
    defaults: { _controller: AppBundle:Challenge:delete }

add_challenge:
    path: /challenge/add
    defaults: { _controller: AppBundle:Challenge:add }

add_answer:
    path: /challenge/answer/add
    defaults: { _controller: AppBundle:Challenge:addAnswer }

view_answers:
    path: /challenge/{id}/answers
    defaults: { _controller: AppBundle:Challenge:viewAnswers }

users:
  path: /admin/listUsers/{type}
  defaults: { _controller: AppBundle:Admin:listUsers, type:2 }

manage_user_activation:
  path: /admin/manage/{id}/{isActive}
  defaults: { _controller: AppBundle:Admin:manageUserActivation }

upgrade_user:
  path: /admin/upgradeUser/{id}
  defaults: { _controller: AppBundle:Admin:updateApprenticeToMaster }

profile:
  path: /user/profile/{id}
  defaults: { _controller: AppBundle:User:getProfileInformation }

editProfile:
  path: /user/editProfile/{id}
  defaults: { _controller: AppBundle:User:editProfile}

vote_answer:
  path: /answer/vote
  defaults: { _controller: AppBundle:ChallengeAnswer:vote }

ranking:
  path: /ranking
  defaults: { _controller: AppBundle:User:getRanking }


