app:
    resource: "@AppBundle/Controller/"
    type:     annotation

register:
    path: /register
    defaults: { _controller: AppBundle:Registration:register }

question_edit:
    path: /question/{cid}/{id}
    defaults: { _controller: AppBundle:Question:edit }