# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        main_provider:
            id: app.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/ 
            security: false
        secured_area:
            pattern: ^/
            anonymous: true

            guard:
                authenticators:
                    - app.form_login_authenticator
                    - app.token_authenticator
                entry_point: app.form_login_authenticator
            #remember_me:
             #   key: abcd123KEY

            provider: main_provider

            switch_user: ~

            logout:
                # The route name the user can go to in order to logout
                path: security_logout
                # The name of the route to redirect to after logging out
                target: homepage

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }